import "./array_nested_prop.test";
import "./array.test";
import "./btn.test";
import "./btn_slot.test";
import "./component_model.test";
import "./computed.test";
import "./directive.test";
import "./form.test";
import "./hello_world.test";
import "./if_else.test";
import "./inplace_if_toggle.test";
// import "./invalid_component.test";
// import "./invalid_event_handler.test";
// import "./invalid_formatter.test";
import "./model.test";
import "./nested_object_prop.test";
import "./object.test";