export enum HTML_TAG {
    div = 1,
    b = "b",
    span = "span",
    input = "input",
    u = "u",
    button = "button",
    table = "table",
    tr = 1,
    td = 1,
    thead = 1,
    tbody = 1,
    tfoot = 1,
    strong = 1,
}